server:
  servlet:
    context-path: /api

excel:
  uploadLocation: src/main/resources/upload
  downloadLocation: src/main/resources/download
  templateLocation: src/main/resources/modules
  reportLocation: src/main/resources/reports

spring:
  datasource:
    url: jdbc:mysql://192.168.91.128:3306/ftpdemo
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.example.demo.dao.mapper: debug
